"""init2winitoday

Revision ID: 32bd3a60260c
Revises: 9ee048831929
Create Date: 2024-01-19 10:31:48.780438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bd3a60260c'
down_revision = '9ee048831929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('members')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
