"""One,Bellator,ACA

Revision ID: 663525f67313
Revises: d25b722963c6
Create Date: 2024-03-03 11:17:12.496489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663525f67313'
down_revision = 'd25b722963c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aca_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('locationCC', sa.String(length=255), nullable=True),
    sa.Column('backgroundImageSrc', sa.String(length=255), nullable=True),
    sa.Column('tapImage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bellator_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('locationCC', sa.String(length=255), nullable=True),
    sa.Column('backgroundImageSrc', sa.String(length=255), nullable=True),
    sa.Column('tapImage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('locationCC', sa.String(length=255), nullable=True),
    sa.Column('backgroundImageSrc', sa.String(length=255), nullable=True),
    sa.Column('tapImage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aca_fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_class', sa.String(length=255), nullable=False),
    sa.Column('red_corner_name', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_name', sa.String(length=255), nullable=False),
    sa.Column('red_corner_country', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_country', sa.String(length=255), nullable=False),
    sa.Column('red_corner_record', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_record', sa.String(length=255), nullable=False),
    sa.Column('red_corner_image', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_image', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['aca_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bellator_fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_class', sa.String(length=255), nullable=False),
    sa.Column('red_corner_name', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_name', sa.String(length=255), nullable=False),
    sa.Column('red_corner_country', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_country', sa.String(length=255), nullable=False),
    sa.Column('red_corner_record', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_record', sa.String(length=255), nullable=False),
    sa.Column('red_corner_image', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_image', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['bellator_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_class', sa.String(length=255), nullable=False),
    sa.Column('red_corner_name', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_name', sa.String(length=255), nullable=False),
    sa.Column('red_corner_country', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_country', sa.String(length=255), nullable=False),
    sa.Column('red_corner_record', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_record', sa.String(length=255), nullable=False),
    sa.Column('red_corner_image', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_image', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['one_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_fights')
    op.drop_table('bellator_fights')
    op.drop_table('aca_fights')
    op.drop_table('one_events')
    op.drop_table('bellator_events')
    op.drop_table('aca_events')
    # ### end Alembic commands ###
