"""Your migration message

Revision ID: 7043c9aa7834
Revises: 697d1d880147
Create Date: 2023-11-13 22:52:39.851667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7043c9aa7834'
down_revision = '697d1d880147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ufc_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('locationCC', sa.String(length=255), nullable=False),
    sa.Column('backgroundImageSrc', sa.String(length=255), nullable=False),
    sa.Column('tapImage', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ufc_fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_class', sa.String(length=255), nullable=False),
    sa.Column('red_corner_name', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_name', sa.String(length=255), nullable=False),
    sa.Column('red_corner_country', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_country', sa.String(length=255), nullable=False),
    sa.Column('red_corner_record', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_record', sa.String(length=255), nullable=False),
    sa.Column('red_corner_image', sa.String(length=255), nullable=False),
    sa.Column('blue_corner_image', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ufc_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ufc_fights')
    op.drop_table('ufc_events')
    # ### end Alembic commands ###
