"""FLASK RESET 

Revision ID: 9d538a89e6ef
Revises: 9ef023fe75d9
Create Date: 2024-01-18 09:50:19.544658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d538a89e6ef'
down_revision = '9ef023fe75d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_league_association')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_league_id_fkey', 'leagues', ['league_id'], ['id'])

    op.create_table('user_league_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='user_league_association_league_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_league_association_user_id_fkey')
    )
    # ### end Alembic commands ###
