"""One,Bellator,ACA23

Revision ID: b62f6f1641ca
Revises: b80f468cf564
Create Date: 2024-03-04 14:22:02.866675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62f6f1641ca'
down_revision = 'b80f468cf564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aca_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('bellator_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('one_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('bellator_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('aca_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
