"""One,Bellator,ACA

Revision ID: b80f468cf564
Revises: 663525f67313
Create Date: 2024-03-04 14:15:49.300161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80f468cf564'
down_revision = '663525f67313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aca_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('bellator_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('one_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('pfl_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfl_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('one_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('bellator_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('aca_events', schema=None) as batch_op:
        batch_op.alter_column('tapImage',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
