"""Your migration message

Revision ID: be121a5e5422
Revises: e9990ffb5b05
Create Date: 2024-02-22 14:17:35.422154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be121a5e5422'
down_revision = 'e9990ffb5b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_league', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('event_league')

    # ### end Alembic commands ###
